email: 'youremail@gmail.com'

data_extraction:
  output_dir: '/data/raw'
  query: 'mRNA[Filter] AND Homo sapiens[Organism]'
  db: 'nucleotide'
  rettype: 'fasta'
  retmax: 100

data_cleaning:
  input_dir: './data/raw'
  output_dir: './data/processed'