email: 'youremail@gmail.com'
project_path: ""

data_extraction:
  output_dir: '/data/raw'
  query: 'mRNA[Filter] AND Homo sapiens[Organism]'
  db: 'nucleotide'
  rettype: 'fasta'
  retmax: 100

data_cleaning:
  input_dir: '/data/raw'
  output_dir: '/data/processed/mRNA'

sequence_translation:
  input_dir: '/data/processed/mRNA'
  output_dir: '/data/processed/proteins'